### ISSUE TITLE
Binary file is not being generate

### ISSUE THREAD

**Issue by bankim** [cylien/dcmtk-3.6.1_20121102#1]
Hi,

I am trying to generate binary file from this project but it is not generating at all. Can you guys please help me on this with binary of this code or how can I generate it.

**Comment by cylien** [comment]
Can you provide the error messages In detail?

**Comment by bankim** [comment]
Yes, Sure.

I used following command but not getting any DCMTK.xcode file inside that. I am using mac osx 10.11.1 
1. ./configure
2. make
3. "sudo make install

I used CMake also to generate the binary but as per document i am not finding any .xcode file there after. See the error below while trying it using CMake,

CMake Warning (dev) at CMake/CheckFunctionWithHeaderExists.cmake:11 (IF):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "HAVE_PROTOTYPE_ISINF" will no longer be dereferenced
  when the policy is set to NEW.  Since the policy is not set the OLD
  behavior will be used.
Call Stack (most recent call first):
  CMake/GenerateDCMTKConfigure.cmake:383 (CHECK_FUNCTIONWITHHEADER_EXISTS)
  CMake/dcmtkPrepare.cmake:309 (INCLUDE)
  CMakeLists.txt:8 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMake/GenerateDCMTKConfigure.cmake:438 (IF):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "C_CHAR_UNSIGNED" will no longer be dereferenced when
  the policy is set to NEW.  Since the policy is not set the OLD behavior
  will be used.
Call Stack (most recent call first):
  CMake/dcmtkPrepare.cmake:309 (INCLUDE)
  CMakeLists.txt:8 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMake/dcmtkTryCompile.cmake:15 (IF):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "HAVE_CXX_BOOL" will no longer be dereferenced when
  the policy is set to NEW.  Since the policy is not set the OLD behavior
  will be used.
Call Stack (most recent call first):
  CMake/GenerateDCMTKConfigure.cmake:455 (DCMTK_TRY_COMPILE)
  CMake/dcmtkPrepare.cmake:309 (INCLUDE)
  CMakeLists.txt:8 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

Configuring done
CMake Error at support/libxml2/CMakeLists.txt:235 (ADD_LIBRARY):
  Cannot find source file:

```
/Users/bankim/Documents/Projects/dcmtk-3.6.1_2/bbbbbbb/support/libxml2/libxml2/libxml/xmlexports.h
```

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Warning (dev) at support/openssl/CMakeLists.txt:412 (ADD_DEPENDENCIES):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "ASM" of target "dcmtkeay" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at support/openssl/CMakeLists.txt:412 (ADD_DEPENDENCIES):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "LINKER_LANGUAGE" of target "dcmtkeay" does not
  exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at support/openssl/CMakeLists.txt:412 (ADD_DEPENDENCIES):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "PROPERTIES" of target "dcmtkeay" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by cylien** [comment]
Sorry, this project only supports Windows Libraries. :)
The message CMP0046 from CMake is due to the version of CMake. This project is only tested on CMake 2.6.

**Comment by bankim** [comment]
Okey, Thanks. Actually we need it for iOS. Is there anything for iOS, so it can help us?

**Comment by cylien** [comment]
There is a solution for compiling the DCMTK in iOS IN CHINESE. http://blog.csdn.net/kesalin/article/details/6955318  Perhaps you can use the Google Translate. :)
